name: Invite user to organization on issue creation

on:
  issues:
    types: [opened]

jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
    - name: Invite user to organization
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_INVITE_TOKEN }}
      run: |
        issue_author=$(jq -r .issue.user.login "$GITHUB_EVENT_PATH")
        org="MCA-CodeHub-MITS"
        curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/orgs/$org/memberships/$issue_author" \
          -d '{"role":"member"}'
